version: '3.8'

services:
  bot:
    build: .
    container_name: ruobr-bot-dev
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env.dev
    volumes:
      - ./data-dev:/app/data

